###############################################################################
# Database configuration

# Connection string is in Go pq driver format:
# host=localhost user=postgres password=2951 dbname=go_backend_uni port=5432 sslmode=disable

[database]

connection_string = "host=localhost user=postgres password=2951 dbname=go_backend_uni port=5432 sslmode=disable"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
###############################################################################
# HTTP server configuration

[http]

server_address = ":8080"
cors_origin = "http://127.0.0.1:5173"
cors_methods = "GET, POST, PATCH, DELETE, OPTIONS"
cors_headers = "Authorization, Origin, Content-Type, Cookie, X-CSRF-Token, Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers"
cors_credentials = "true"
secrete_key = "secrete-key"
session = "mysession"
store = "secrete"

###############################################################################
# Security

[security]

secrete_key = "secrete_key"
###############################################################################